## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[build]
  command = "yarn build && cd functions/node-fetch && yarn"
  functions = "functions"
  publish = "dist"