## api redirect.
[[redirects]]
  from = "/api/*"
  to = "https://alorice.xyz/api/:splat"
  status = 200
## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200