## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
# api redirect.
[[redirects]]
  from = "/api/*"
  to = "https://chat-app-v.herokuapp.com/:splat"
  status = 200
