export default class Notification {
  static NOTIFICATION_MISS_CALL = 'NOTIFICATION_MISS_CALL';
  static NOTIFICATION_INCOMING_CALL = 'NOTIFICATION_INCOMING_CALL';
  static NOTIFICATION_GOING_CALL = 'NOTIFICATION_GOING_CALL';
  static NOTIFICATION_DECLINE_CALL = 'NOTIFICATION_DECLINE_CALL';
  static NOTIFICATION_ENDED_CALL = 'NOTIFICATION_ENDED_CALL';
  static NOTIFICATION_FRIEND_REQUEST = 'NOTIFICATION_FRIEND_REQUEST';
  static NOTIFICATION_MEMBER_ADDITION = 'NOTIFICATION_MEMBER_ADDITION';
}
